<a href="https://colab.research.google.com/github/nikolas-joyce/autofill_my_brain/blob/master/PyTorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hi Pytorch.")

Hi Pytorch.


In [3]:
# ! pip install ffn

In [1]:
## 00. PyTorch Fundamentals
## https://www.learnpytorch.io/00_pytorch_fundamentals/
##


import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import ffn, bt
print(torch.__version__)




2.5.1+cu121


In [6]:
## Intro to Tensors

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [12]:
scalar.item()


7

In [13]:
#Vector

vector = torch.tensor([7,7])
vector


tensor([7, 7])

In [16]:
vector.ndim

1

In [17]:
vector.shape

torch.Size([2])

In [19]:
# MATRIX
MATRIX = torch.tensor([[7,8],[11,10]])
MATRIX

tensor([[ 7,  8],
        [ 1, 10]])

In [20]:
MATRIX.ndim

2

In [28]:
MATRIX.size()


torch.Size([2, 2])

In [24]:
MATRIX.shape

torch.Size([2, 2])

In [23]:
MATRIX[0]

tensor([7, 8])

In [35]:
TENSOR = torch.tensor([[[1,2,3],[3,6,9],[2,4,5],[2,4,5]]])

In [36]:
print(TENSOR.ndim)
print(TENSOR.size())
print(TENSOR.shape)

3
torch.Size([1, 4, 3])
torch.Size([1, 4, 3])


In [37]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5],
        [2, 4, 5]])

## Randon Tensors

Random tensors are important because neural networsk learn by starting with random numbers then adjusting those numbers to better represent the data.

Start with random numbers --> look at data --> update random numnbers -->look at data --> update random numbers.

In [ ]:
#